-- UpcycleConnect Seed Data
USE upcycleconnect;

-- ===========================
-- CATEGORIES
-- ===========================
INSERT INTO categories (created_at, updated_at, name, slug, description, icon, color, is_active) VALUES
(NOW(), NOW(), 'Mobilier', 'mobilier', 'Meubles et décoration', 'sofa', '#8B5CF6', 1),
(NOW(), NOW(), 'Électronique', 'electronique', 'Appareils électroniques', 'cpu', '#3B82F6', 1),
(NOW(), NOW(), 'Vêtements', 'vetements', 'Mode et accessoires', 'shirt', '#EC4899', 1),
(NOW(), NOW(), 'Livres & Médias', 'livres-medias', 'Livres, DVD, jeux', 'book', '#F59E0B', 1),
(NOW(), NOW(), 'Bricolage', 'bricolage', 'Outils et matériaux', 'wrench', '#10B981', 1);

-- ===========================
-- USERS (password = bcrypt of "test123" for test users, "admin123" for admin)
-- The actual hashes are generated by Go at startup if DB is empty
-- These are just for documentation - the Go seed function handles insertion
-- ===========================

-- Note: Users, listings, workshops, scores, notifications are seeded by Go at startup
-- (see cmd/main.go seedData function)
